on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-go@v2
        with:
          stable: false
          go-version: '1.18.0-beta1'

      - run: make

      - uses: actions/upload-artifact@v2
        with:
          name: protonutils
          path: cmd/protonutils/protonutils
