on:
  push:
    tags: 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: 1.23

      - run: |
          sudo apt-get update
          sudo apt-get -y install upx-ucl

      - run: make release

      - uses: softprops/action-gh-release@v2
        with:
          files: cmd/protonutils/protonutils
