on:
  push:
    tags: 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-go@v2
        with:
          stable: false
          go-version: '1.18.0-beta1'

      - name: Install Build Dependencies
        run: |
          sudo apt-get update
          sudo apt-get -y install upx-ucl nodejs npm libgtk-3-dev libwebkit2gtk-4.0-dev

      - run: make release

      - uses: softprops/action-gh-release@v1
        with:
          files: cmd/protonutils/protonutils
