on:
  push:
    tags: 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-go@v2
        with:
          go-version: '^1.16.8'

      - run: make release

      - uses: actions/upload-artifact@v2
        with:
          name: list-proton-versions
          path: cmd/list-proton-versions/list-proton-versions

      - uses: softprops/action-gh-release@v1
        with:
          files: list-proton-versions-*
